# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8c5bdf7f0e9c4d29d03c6551aaca1091fe5f73413240f2cf882cb720bb00783a4ea5454a313b5c255ee48c8988e3e656e2245eed2f68afab234363fc3d50ab8e

test:
  secret_key_base: 49a97a803cf1a6819a451a149938f31778a57465efc10c332f96fe1d8d135151a7686da7e0b4cb6b78fa00c729faf600849f618ef851e88fead48918cd9ffad9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
